### ISSUE TITLE
Why no ArrayAccess?

### ISSUE THREAD

**Issue by jfern01** [mediact/data-container#6]
Is there any technical reason why DataContainer object doesn't implement ArrayAccess? It seems like it would be easy enough to implement. I'm totally willing to contribute code, I just wanted to know if this was planned or not.

**Comment by johmanx10** [comment]
Hello @jfern01 ,
We have discussed whether `ArrayAccess` would be an interesting interface to support in the past. Our conclusion is that we do not wish to support this in the current package. The reasoning behind this is that a data container is something different from an array, in that you can access nodes and leafs using patterned paths. The question then becomes: what would you expect to happen in the following scenarios:

```php
<?php
/** @var DataContainerInterface $container */
$container['fruits.foo.type'] = 'apple';
$apples = $container['fruits.*'];
```
Would this under the hood reflect array A or array B?
```php
<?php
// Array A:
$data = [
    'fruits' => [
        'foo' => [
             'type' => 'apple'
        ]
    ]
];

// Array B:
$data = [
    'fruits.*' => ['foo', 'bar', 'baz'],
    'fruits.foo.type' => 'apple'
];
```

Since either array is reasonably debatable and defendable at the same time, we chose to not implement this, to prevent obscure and unexpected behavior.

Additionally, we believe that if this is functionality that would improve your use of data containers, this can be easily added using a decorator around a data container, implementing both the data container interface and `ArrayAccess`, complemented by an implementation of the factory interface. The package currently holds a decorator trait, in order to more easily create extended functionality on top of data containers. See also https://github.com/mediact/data-container#creating-a-decorator

I hope that this response satisfies your question and would still welcome code improvements. In the case of your current feature request, I suggest introducing a separate package under `<vendor>/data-container-array-access` or something similar.

Sincerely,

Jan-Marten de Boer
MediaCT

**Comment by jfern01** [comment]
That was a very technical answer, I appreciate that. I'll close the issue now, thanks.
